apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: max-weather
  namespace: max-weather
  labels:
    app.kubernetes.io/name: max-weather
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: max-weather
